pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.7.0'
}

includeBuild('../dialoguestudio') {
    dependencySubstitution {
        substitute module('com.benji.dialoguestudio:dlgstd') using project(':')
    }
}

includeBuild('../titlestudio') {
    dependencySubstitution {
        substitute module(
                'com.benji.titlestudio:ttlstd'
        ) using project(':')
    }
}